apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-vpn-service"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: "{{ .Release.Name }}-vpnserver"
  ports:
  - protocol: {{ index .Values.service.ports 0 "protocol" }}
    port: {{ index .Values.service.ports 0 "port" }}
    targetPort: {{ index .Values.service.ports 0 "targetPort" }}
    nodePort: {{ index .Values.service.ports 0 "nodePort" }}
  externalTrafficPolicy: Local
